# Generated by Django 3.2.19 on 2024-01-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_academicstaff_adminmanager_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstaff',
            name='role',
            field=models.CharField(default='academic_staff', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='adminmanager',
            name='role',
            field=models.CharField(default='admin', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', max_length=20, verbose_name='角色'),
        ),
    ]
