# Generated by Django 3.2.19 on 2024-01-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20240103_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='考试标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration_minutes', models.IntegerField(verbose_name='考试时长（分钟）')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course', verbose_name='科目')),
                ('questions', models.ManyToManyField(related_name='exam_questions', to='exam.QuestionBank')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
            },
        ),
    ]
